---
driver:
  forward_agent: yes
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero
  chef_client_path: "c:/opscode/chef/bin/chef-client.bat"

platforms:
  - name: windows_2008r2-chef11
    driver_config:
      box: win2k8r2
      box_url: https://s3-us-west-2.amazonaws.com/chef-box-cutter/windows/virtualbox4.3.20/eval-win2008r2-datacenter-nocm-1.0.3.box  
      gui: true
    provisioner:
      require_chef_omnibus: 11.16.4
      chef_client_path: "c:/opscode/chef/bin/chef-client.bat"

suites:
  - name: default
    run_list:
      - recipe[windows_firewall::default]
